### ISSUE TITLE
Image and Icon not working in 1.3.0 snapshot

### ISSUE THREAD

**Issue by transparentech** [damoncourtney/installjammer#10]
I'm using the 1.3.0 snapshot (from 16-July-2010) on Linux/Mac to build an installer for Linux-x86.

The building works fine (on both Linux/Mac), but running the installer on Linux fails with this message:

<pre>
couldn't recognize image data
    while executing
"image create photo -data iVBORw0KGgoAAAANSUhEUgAAAKQAAAE6CAYAAACYrvnGAAAAAXNSR0IArs4c6QAAAAZiS0dEAP8A/wD/oL2nkwAAAAlwSFlzAAALEwAACxMBAJqcGAAAAAd0SU1FB..."
    (procedure "InitGui" line 58)
    invoked from within
"InitGui"
    (procedure "::InstallJammer::InitializeGui" line 9)
    invoked from within
"::InstallJammer::InitializeGui "
    (procedure "::InstallJammer::InitInstall" line 68)
    invoked from within
"::InstallJammer::InitInstall"
    (file "/installkitvfs/main.tcl" line 27715)
</pre>

When I remove any settings for the Application Information -> Image and Icon fields, the installer runs fine. With Image and Icon set, Preview Pane shows the correct image. It is only in the final installer that the error seems to arise. So my guess is that it has something to do with the encoding of the images in the installer itself. 

I've tried using relative and absolute paths to the images as well as virtual text to specify the images but none of them work. The installer will only run without any Image or Icon specified.

Let me know if I can add any more information on this issue.

**Comment by damoncourtney** [comment]
Are you on 32 or 64 bit Linux?  Just want to make sure.  I think the problem may be in differences in the platform binaries.  The Linux ones may not have gotten the proper updates with the last round of builds, so they may be failing on the image data.

Are you using PNGs or GIFs here?

**Comment by transparentech** [comment]
I run InstallJammer on 64 bit Linux. I didn't try it on 32 bit Linux.  But I'm building the Linux-x86 platform installer, not the Linux-x86_64, as the application I'm bundling works on both platforms, I only want to distribute 1 installer for that works on both platforms.

I'm using PNGs.

**Comment by damoncourtney** [comment]
Can you send me the PNG file you are using in your project?  I just tested with a simple PNG file, and it seems to work fine.  I want to make sure we're both using the same data.

**Comment by transparentech** [comment]
I just PMed you the files I'm using.

**Comment by thefallguy** [comment]
I am having this issue too. Any progress on a fix?

**Comment by damoncourtney** [comment]
What version of the snapshot are you using?  I just tested on my Ubuntu VM with the images transparentech sent me, and I didn't see any issue.  Does this occur as soon as you launch the installer?

**Comment by damoncourtney** [comment]
Ok.  I got the failure when running on a 64 bit machine.  Let me keep testing from there.

**Comment by damoncourtney** [comment]
Ok.  I recompiled the Linux binaries for both 32 and 64 bits.  That should fix things.  Grab the latest 1.3 snapshot and give it a try.

**Comment by thefallguy** [comment]
I am actually building on the installer on Windows (7, 32-bit) for deployment on Linux (Ubuntu 10.04, 32-bit). Will this fix the issue? I'll give it a try and let you know.

**Comment by thefallguy** [comment]
I confirm that this build now displays the images correctly.

**Comment by transparentech** [comment]
Works for me too. I've built the Linux installer on both a Mac and a Linux machine and the image and icon in the installer work fine now. Thanks for the fix.
