### ISSUE TITLE
Cannot execute binary file

### ISSUE THREAD

**Issue by gboelter** [damoncourtney/installjammer#100]
I have created several installers for different Linux-versions (Fedora, Debian, Ubuntu) from the same source. Most of them are working, not perfect, but at least working.

What's not working is the installer for Fedora 64 Bit (tested with a clean installation using the Fedora 13 Desktop Edition and even Fedora 14). There I got only the message 'cannot execute binary file'! 

I guess it's more a tcl-problem, bc on my own machine with Fedora 14/64 it's working. So I think something is missing, but what could it be? And it's working too with a clean install of 'Fedora 14 KDE Spin'.

The problem only appears with 64 Bit, the installer for 32 Bit runs well.

It happend under 1.3.0 (Build 6c376a1) and 1.2.15 (Build c2cf97c).

**Comment by sdelmas** [comment]
Are you using a 64 bit installer? Most current 64 bit systems no longer ship with 32 bit libs, so the installer itself needs to be the 64 bit version. Just a thought.

Sven

**Comment by gboelter** [comment]
Hi Sven,
yes, I have tried them both, the 32 bit installer is working well under 64 bit Fedora, the 64 bit installer still 'cannot execute binary file'. I've tried IJ 1.2.15 and even IJ 1.3.0, but there is no difference.

Guenther

**Comment by sdelmas** [comment]
Hm... not sure... I never tried it on Fedora. I know it works fine on 64 bit Redhat, Suse and Ubuntu. Sounds like the generated executable isn't even recognized then. What does 'file installer' say about the executable? If you do an strace on the run, is there anything standing out (what's the last set of files the installer is trying to access). 

Sven

**Comment by gboelter** [comment]
Sorry Sven,
I don't have experiences with strace, so I have tried a simple 'strace ./ERPel64-0.84.001-Fedora-Linux-x86_64-Install' and here is the output:

[root@localhost Downloads]# strace ./ERPel64-0.84.001-Fedora-Linux-x86_64-Install 
execve("./ERPel64-0.84.001-Fedora-Linux-x86_64-Install", ["./ERPel64-0.84.001-Fedora-Linux-"...], [/\* 44 vars */]) = -1 ENOEXEC (Exec format error)
dup(2)                                  = 3
fcntl64(3, F_GETFL)                     = 0x8002 (flags O_RDWR|O_LARGEFILE)
fstat64(3, {st_mode=S_IFCHR|0620, st_rdev=makedev(136, 1), ...}) = 0
mmap2(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0xb7879000
_llseek(3, 0, 0xbf9596dc, SEEK_CUR)     = -1 ESPIPE (Illegal seek)
write(3, "strace: exec: Exec format error\n", 32strace: exec: Exec format error
) = 32
close(3)                                = 0
munmap(0xb7879000, 4096)                = 0
exit_group(1)                           = ?

Guenther

**Comment by sdelmas** [comment]
Is this the 32 or the 64 bit strace?

**Comment by damoncourtney** [comment]
Is the Fedora installation 32 or 64 bit?  A 64 bit installer definitely will not run on a 32 bit Fedora, and there's a good chance that a 32 bit installer will not work on a 64 bit Fedora.  Most of the Linux distros no longer ship 32 bit compatibility libraries with their 64 bit installations, so 32 bit programs won't work.

**Comment by gboelter** [comment]
No, we are talking about a 64Bit Installer on a 64Bit Fedora Linux/

**Comment by damoncourtney** [comment]
Can you run InstallJammer itself on this system?  Try running

./Binaries/Linux-x86_64/installkit

and see if the install binary interpreter will even come up.

**Comment by gboelter** [comment]
No, ./Binaries/Linux-x86_64/installkit is not working too as you can see here ...

[root@localhost Linux-x86_64]# ./installkitU
bash: ./installkitU: cannot execute binary file

[root@localhost bin]# /usr/bin/strace ./installkit
execve("./installkit", ["./installkit"], [/\* 44 vars */]) = -1 ENOEXEC (Exec format error)
dup(2)                                  = 3
fcntl64(3, F_GETFL)                     = 0x8002 (flags O_RDWR|O_LARGEFILE)
fstat64(3, {st_mode=S_IFCHR|0620, st_rdev=makedev(136, 1), ...}) = 0
mmap2(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0xb775c000
_llseek(3, 0, 0xbfee8dac, SEEK_CUR)     = -1 ESPIPE (Illegal seek)
write(3, "strace: exec: Exec format error\n", 32strace: exec: Exec format error
) = 32
close(3)                                = 0
munmap(0xb775c000, 4096)                = 0
exit_group(1)                           = ?
[root@localhost bin]# 

Looks for me like a problem with Fedora. For a test, I have installed Fedora 14 (64 Bit) on a harddisk using there Live-CD. there it's not working. Today I have installed  Fedora 14 (64 Bit) from there regular DVD and now it's working well. The MD5SUM for both ISO's was ok, so it must be any other problem.

Thanks for the support and a big THANKS for InstallJammer!

Guenther
