### ISSUE TITLE
Save "Virtual Text Strings" to an external file.

### ISSUE THREAD

**Issue by magmax** [damoncourtney/installjammer#102]
Hello.

You need some programming skills to make complex installers. So, often some developers will make the changes, but the usually knows only one or two languages.

I think it would be very useful if you could download the "Virtual Text Strings" into a file, in order to send it to the translation team. It would be better if you could do that by language.

And... well, more for my wish list: to import and merge external "Text Strings" files...

Thank you very much.

**Comment by damoncourtney** [comment]
You actually can create your own message catalog files within your project directory if you like.  InstallJammer will pick up any *.msg files in your project directory and load them into your installer.  I could see where it might be useful to export and import a message catalog though.

**Comment by magmax** [comment]
Hmmm.... that is much better :D

I think It is not necessary to use the import/export button then.

Congratulations for such a good program.
