### ISSUE TITLE
Add directory-related conditions

### ISSUE THREAD

**Issue by psiha** [damoncourtney/installjammer#15]
- directory exists
- directory is empty
- have read/write/... premission for directory

**Comment by damoncourtney** [comment]
This can already be done with the existing File conditions.  The File Exists condition will tell you if the path exists whether it's a file or directory, and the File Permission condition can tell you whether the directory has the permission you need.

The only thing missing is telling whether a directory is empty or not.  I suppose this could all be rolled into a Directory Test condition though.  I'll give it some thought.

**Comment by damoncourtney** [comment]
I just pushed a new Directory Test condition that should satisfy your needs.
