### ISSUE TITLE
Directory structure not uninstalled

### ISSUE THREAD

**Issue by psiha** [damoncourtney/installjammer#17]
When, for example, "C:/Program files/SomeCompany/SomeProduct" is chosen as the installation target folder and neither SomeCompany or SomeProduct exist the installation will only write the SomeProduct directory in the log and the uninstaller will then not delete the SomeCompany directory even if empty

**Comment by damoncourtney** [comment]
The company directory is treated a little differently, but it should be deleted in the end if it's empty.  This is most likely a bug.

**Comment by damoncourtney** [comment]
Just pushed a fix for this.  Please grab the latest snapshot and give it a try.

**Comment by damoncourtney** [comment]
Calling it fixed.
