### ISSUE TITLE
Support for formatted readme

### ISSUE THREAD

**Issue by psiha** [damoncourtney/installjammer#18]
Please add support for formatted readmes that optionally get opened on the last pane (e.g. RTF, HTML...)...

**Comment by damoncourtney** [comment]
This is probably not going to happen.  I don't have a widget in Tk that provides HTML or RTF rendering, and the amount of time it would take to write one would be much better spent on other things.

As it stands now, you can easily include a Launch File action to launch a web browser or PDF reader to view your README if that is the format you want.  InstallJammer will probably only ever support plain text for the internal reader.

**Comment by psiha** [comment]
Is it then maybe possible to specify a (monospaced) font for the internal reader?
