### ISSUE TITLE
Clicking finish does not close the last pane if the readme is displayed

### ISSUE THREAD

**Issue by psiha** [damoncourtney/installjammer#19]
If the user opts to have the readme displayed and then clicks finish the IJ window/pane should not stay visible in the background (if the process needs to remain active to actually display the readme it should still hide the main window)

**Comment by damoncourtney** [comment]
I wouldn't expect this behavior at all.  I guess it's just a difference of opinion.  Most installer don't have a window that displays the README file, they simply fire off Notepad or a web browser or whatever to display their README.

You can do this if you like, but I think I'll keep the current behavior as it is with regards to the internal README window.
