### ISSUE TITLE
The Create File Link action should log the link to the uninstaller

### ISSUE THREAD

**Issue by damoncourtney** [damoncourtney/installjammer#2]
Create File Link does not provide an option to include the link in the uninstaller.

**Comment by thefallguy** [comment]
Any progress on this? This would be a really useful addition, and save me having to code a delete in the uninstaller for each link - which is a real maintenance pain.

**Comment by damoncourtney** [comment]
Just pushed a fix.  Should be in the 1.2 snapshot shortly.

**Comment by thefallguy** [comment]
Is this going to make it into 1.3 - which is what I am using...
