### ISSUE TITLE
Persistent file/folder exclusion filters

### ISSUE THREAD

**Issue by psiha** [damoncourtney/installjammer#21]
Please add the option to save file/folder exclusion filters (so that, for example, one does not have to constantly type in the .svn filter each time a new folder is added to installer).

**Comment by damoncourtney** [comment]
Under Application Information -> Project Preferences, there are two options:  Ignore Directories and Ignore Files.  These options a ; separated list of regular expressions to match against when searching recursively through directories.  I believe this will do what you want.
