### ISSUE TITLE
Get Previous Install Info does not create any virtual text

### ISSUE THREAD

**Issue by tbillet** [damoncourtney/installjammer#25]
When using the Get previous install info component, the ReadInstallInfo API does not set the different variables.

**Comment by damoncourtney** [comment]
Just pushed a fix for this.  The API should now set all the variables expected from Check for Previous Install.  The docs will be updated before the next release to explain more about what the API is doing now, but it basically does what you wanted, which is set the Exists, DirExists variables, etc...
