### ISSUE TITLE
When deleting a file using the Delete key on keyboard, two dialogs appear

### ISSUE THREAD

**Issue by sdeschenes** [damoncourtney/installjammer#28]
When you delete a file from a file group using the Delete key on the keyboard, a dialog will appear asking if you are sure you want to delete the file. After clicking the Yes button on the dialog, another dialog appears asking the same question. Clicking Yes on the second dialog will proceed with deleting the file. Now, if you right-click on the file and select Delete, clicking Yes will delete the file and a second dialog will not appear.

**Comment by damoncourtney** [comment]
Pushed a fix for this.  Should be in the snapshot shortly.

**Comment by sdeschenes** [comment]
I am verifying this issue is fixed in the latest snapshot. The double delete dialog no longer appears when deleting a file using the "Delete" key on the keyboard.
