### ISSUE TITLE
Message "Directory is not empty" is not internationalized

### ISSUE THREAD

**Issue by brunobastosg** [damoncourtney/installjammer#3]
When I uninstall my application, if there are new files in its directory, the uninstaller presents the message "/path/to/directory is not empty" message. However, I need to change it to a more user-friendly message.

I found out that this message is hard-coded in the UninstallSelectedFiles.action file. So, I'd like to ask you to internationalize it in future versions.

**Comment by damoncourtney** [comment]
Just pushed a fix for this.

**Comment by brunobastosg** [comment]
Thank you! Is the fix available in version 1.3 also?

**Comment by damoncourtney** [comment]
Not yet, but I will port it over.

**Comment by damoncourtney** [comment]
Ported this to 1.3.  Should be in the snapshot shortly.
