### ISSUE TITLE
Unable to add ActionGroup inside Pane

### ISSUE THREAD

**Issue by nikhil123** [damoncourtney/installjammer#30]
Requirement: Enable/disable Next Button of a Pane based on widgets selection/deselction present on 
                    the same pane. 

Next Button on a Pane is enabled/disabled on the basis of ActionGroup(containing 2 Actions). If i create and add my action group to "Action Groups" Category, Next Button specific to pane is not available to specify ID or alias (as it is specific to a pane). I can't add my actiongroup inside a Pane neither widget action property be set to execute multiple actions.

**Comment by damoncourtney** [comment]
If you want to execute an Action Group, you add an Execute Action action to your pane that executes the ID or Alias of your Action Group.  The Action Group will respond to wherever it is executed.  Meaning that if you modify the Next button to disable it, it will disable it on the pane you are currently on.

Actually, the Next button lives outside of the panes, so disabling the Next button will disable it completely until you re-enable it later.  It will not re-enable itself on the next pane.

**Comment by nikhil123** [comment]
What I did:

1) created New Project

2) Inserted Custom Blank Pane2 (say MyPane ) after Choose Components Pane  
                                                                                 (available by default).
   My Pane has Back,Next and Cancel Button present by default.

3) In MyPane, i added 2 widgets of type checkButton

4) On each checkButton widget i specify Action property with ID of  an ActionGroup 
                                                                               (say  MyActionGroup) .

5) In MyActionGroup, i want to enable Next Button of MyPane (as created in step2) if 
   any of checkbutton is selected. If user deselects both, Next Button of MyPane 
  should be disabled so that user cannot move forward with the Installation Process
  and cannot move to next screen.

Problem: 
In MyActionGroup i added 2 Actions of Modify Widget (say Action1 and Action2). Action1 will disable Next button of MyPane by checking state of checkbuttons of MyPane. Similarly Action2 will enable Next Button.

But Next Button is specific to MyPane with no ID/alias name available and cannot be specified in AdvancedProperties->widget Property of Modify widget Actions?????

**Comment by damoncourtney** [comment]
The Next button does not exist on your pane.  The Next button exists outside of the panes.  It is common to all panes.  So, you can disable the Next button on any pane.  It will affect all panes at once because there is no per-pane Next button.

**Comment by nikhil123** [comment]
I am able to add Action(Modify Widget) inside a Pane and disable/enable next button.

But how to do the same from MyActionGroup. The dropdown list of AdvancedProperties->widget Property of Modify widget Action does not display next button in case of MyActiongroup.

**Comment by damoncourtney** [comment]
The drop down list is just a suggestion list.  You can type "Next Button" into the Widget property and it will do the same thing.  The action inside your action group just doesn't know where it will be executed, so it can't guess at the list of widgets to modify.  You have to specify it yourself.

**Comment by nikhil123** [comment]
Thanks Damon. Its Done. May be this needs to be mentioned somewhere in documentation. good work damon !!!!
