### ISSUE TITLE
Characters in app name don't display properly in uninstaller

### ISSUE THREAD

**Issue by brunobastosg** [damoncourtney/installjammer#31]
This happens only in Windows. My application name has latin characters. The installer runs fine, all messages display properly, including the application name.

When I run the uninstaller, however, the latin characters in the application name only don't display properly. ç becomes Ã§, ã becomes Ã£, etc.

The other latin characters display just fine.

It's not only in the title bar, but everywhere the app name is used.

**Comment by damoncourtney** [comment]
Just pushed a fix for this.  Should be in the latest 1.2 snapshot already.

**Comment by brunobastosg** [comment]
Alright, thank you! Gonna try it soon!

**Comment by brunobastosg** [comment]
Just tested it and it's working perfectly. Thanks!
