### ISSUE TITLE
Linux-x86 installer fails to run on 64-bit system

### ISSUE THREAD

**Issue by thefallguy** [damoncourtney/installjammer#34]
We are installing a 32-bit application that runs on a 64-bit system. Using IJ1.2.x, we could happily run the 32-bit installer on the 64-bit system.

However, with the 1.3 build (downloaded this week), the installer silently fails on the 64-bit system. Running strace shows that an open call for /lib/ld-linux.so.2 is failing. As I said, this used to work, so can it be made to work again?

**Comment by damoncourtney** [comment]
I can't imagine this used to work.  32 bit binaries will only work on 64 bit systems if the 32 bit compatibility libraries have been installed.  More and more distros are shipping 64 bit versions without the 32 bit libraries.  My guess is that is what is happening here, but there's absolutely nothing in the 1.2 tree that would (or could) prevent this from happening either.

**Comment by thefallguy** [comment]
Ahh, thanks for the info - that is likely to be the issue. I will check with the guy that reported it (although he is the same guy that reported it working before...)

**Comment by damoncourtney** [comment]
Closing this out.
