### ISSUE TITLE
Partial desktop installation in Linux 

### ISSUE THREAD

**Issue by pns** [damoncourtney/installjammer#35]
There are at least three problems with the desktop installation of InstallJammer Version 1.2.15b1, (Build 84d2bf4) in CentOS 5.5 (using Gnome 2.16.0):

(a) No application launcher is created in the Gnome "Start Menu", despite "Help", "User Guide" and "Uninstall" menu entries being created).

(b) The xdg-utils are installed at a different location to that recorded in the menu entries. More specifically, the xdg-utils are installed at 

```
<%InstallDir%>/lib/packages/xdg-utils
```

and not under

```
<%InstallDir%>/Binaries/Linux-x86/xdg-utils
```

that the program expects. This way, the menu entries for Help and the User Guide do not work.

The workaround is to go to the menu entry and manually change the location of xdg-open.

(c) The xdg-utils are not set to executable and one has to change the corresponding file permissions.

**Comment by damoncourtney** [comment]
These should be fixed in the latest release.
