### ISSUE TITLE
Build Installers selection is not saved in Linux

### ISSUE THREAD

**Issue by pns** [damoncourtney/installjammer#36]
InstallJammer Version 1.2.15b1 (Build 84d2bf4) does not save user preferences of the Run Build > Build Installers > Platforms to build tab, in CentOS 5.5.

**Comment by damoncourtney** [comment]
The Build Platforms list never gets saved.  This list only counts for the current session.  If you want to not build something permanently, go into the Platforms list and mark that platform as inactive.

This is not a bug.
