### ISSUE TITLE
1.2.15b1  can't use non-numeric string as operand of "+"

### ISSUE THREAD

**Issue by leon57** [damoncourtney/installjammer#37]
If using Build Separate Archives. The builder throws an error can't use non-numeric string as operand of "+". See also (http://www.installjammer.com/forums/viewtopic.php?f=5&t=1789&start=0&st=0&sk=t&sd=a) and (http://www.installjammer.com/forums/viewtopic.php?f=1&t=1680&start=0&st=0&sk=t&sd=a)

**Comment by damoncourtney** [comment]
Just pushed a fix for this.

**Comment by leon57** [comment]
The fix works.
