### ISSUE TITLE
IP Validation

### ISSUE THREAD

**Issue by afroz007** [damoncourtney/installjammer#40]
for my Project i am taking input from user such as:
1. DATABASE IP
2. DATABASE PORT
3. DATABASE NAME
etc

using message field in console mode, i am able to validate for not null, as option is available for that but not able to validate IP with valid IP. if possible Please let me know i stuck to this issue.

Thanks & Regards 
Afroz Ansari

**Comment by damoncourtney** [comment]
This is something probably best discussed on the forum, as it's not really an issue with IJ, just something you want to know how to do.

http://www.installjammer.com/forums/
