### ISSUE TITLE
Linux command line doesn't allow / options anymore in beta version 1.2.15b1

### ISSUE THREAD

**Issue by techie45** [damoncourtney/installjammer#41]
I tried the new beta version 1.2.15b1 and it seems like the linux version doesn't support command line options with / any more. Is this deliberate? My installer calls a bunch of other installers with the same command line for both windows and linux, and now that doesn't work any more. I know linux documentation specifies -- options, and I'd like to know if I should have separate command lines for the two OS's or if both styles will be supported in the future.

**Comment by damoncourtney** [comment]
Grab the latest 1.2 snapshot.  Should have this fixed. 0-]

**Comment by techie45** [comment]
Thanks, will give it a try and let you know if there are any problems.
