### ISSUE TITLE
Attempt to add group and files fails.

### ISSUE THREAD

**Issue by pdxNorman** [damoncourtney/installjammer#43]
Attempt to add group and files fails.

I successfully created several groups and files. When I later attempted to add a new group, the contents of the Groups and Files pane was empty and any attempt to add a new group or failed resulted in the generation of errors. Unfortunately, there is no way to cut and paste the error message here and there is no way to attach a screenshot.

**Comment by damoncourtney** [comment]
Can you maybe paste the error or send a screenshot in a post on the forums?  I'd really like to see the error.  Also, what version and platform are you on?

**Comment by pdxNorman** [comment]
I'm running Windows XP Pro SP3.

I'm running version 1.2.15B1 (Build 84d2bf4).

I'll try to post the screenshot on the forums in a few minutes and let you know when it's there. This application if perfect for my requirement if I can get past this and other minor problems.

**Comment by damoncourtney** [comment]
Definitely join the forum and post over there.  I'm just about ready to release 1.2.15, but if what you have are some small bugs, I might be able to get them fixed tonight before the release next week.

**Comment by pdxNorman** [comment]
Damon,

I've added a snapshot in the forum. I appreciate any help you can offer. I probably did something wrong, but if I could recover without having to recreate the entire project I'd be very happy.

**Comment by damoncourtney** [comment]
Very odd.  Something as simple as adding something to a file group should NOT be failing.

**Comment by pdxNorman** [comment]
I rebooted my machine and the problem still persists on all projects including the simple tutorial project.
