### ISSUE TITLE
kdesu no more in path in KDE4

### ISSUE THREAD

**Issue by xunile** [damoncourtney/installjammer#47]
I report this problem again as it still exists in 1.2.15b1 ...

In KDE4, kdesu (used by IJ to gain root privileges) is no more in the PATH as - if I am not wrong - KDE team plans to replace it by policykit (see http://www.nabble.com/-Cooker--kdesu-on-KDE4-td18755889.html).

The resulting problem is that nothing happens when launching my installer from a file explorer in a default KDE4 install ...

kdesu is still provided but is located in /usr/lib/kde4/libexec/kdesu OR /usr/lib64/kde4/libexec/kdesu, so I propose the attached patch which looks for kdesu in these directories.

<pre>
--- common_original.tcl 2010-05-25 18:56:03.000000000 +0200
+++ common.tcl  2010-05-27 10:36:42.000000000 +0200
@@ -3603,9 +3603,9 @@
     if {$info(GuiMode)} {
         ## Try to find a graphical SU utility we can use.
         if {[::InstallJammer::GetDesktopEnvironment] eq "Gnome"} {
-            set list {gksudo gksu gnomesu kdesudo kdesu xsu}
+            set list {gksudo gksu gnomesu kdesudo kdesu /usr/lib/kde4/libexec/kdesu /usr/lib64/kde4/libexec/kdesu xsu}
         } else {
-            set list {kdesudo kdesu gksudo gksu gnomesu xsu}
+            set list {kdesudo kdesu /usr/lib/kde4/libexec/kdesu /usr/lib64/kde4/libexec/kdesu gksudo gksu gnomesu xsu}
         }
 
         foreach app $list {
@@ -3613,7 +3613,7 @@
             
             set cmd [list $app $cmdline]
             catch {exec $app --help} help
-            if {$app eq "kdesu" || $app eq "kdesudo"} {
+            if {$app eq "kdesu" || $app eq "kdesudo" || $app eq "/usr/lib/kde4/libexec/kdesu" || $app eq "/usr/lib64/kde4/libexec/kdesu"} {
                 set cmd [linsert $cmd 1 -d -c]
                 if {$msg ne "" && [string match "*--comment*" $help]} {
                     set cmd [linsert $cmd 1 --comment $msg]
</pre>

I think a better solution would be to make your own window to gain root privileges so you will not depend on any external tool. However I don't know how easy it is ?

Link to the corresponding thread on the forum: http://www.installjammer.com/forums/viewtopic.php?f=1&p=8956

**Comment by damoncourtney** [comment]
Fixed.  Should be in the release shortly.
