### ISSUE TITLE
KDE4 konsole doesn't support Title option anymore

### ISSUE THREAD

**Issue by xunile** [damoncourtney/installjammer#48]
I still face this problem with the latest IJ (1.2.15b1) : the "konsole" program doesn't support -T (title) option anymore.
It means that IJ fails to launch any external program. Eg with latest IJ :
<I><pre>10/19/2010 11:58:42AM - Executing Command Line: konsole -T {Installing ntp ...} -e /root/tmp/ijtmp_DEA6EECF-8F03-0B99-B2C9-35D323F99C03/8090-1.sh
10/19/2010 11:58:42AM - Error while executing: konsole: Unknown option 'T'.
konsole: Use --help to get a list of available command line options.</pre></I>

Also note that KDE4 config directory is now ".kde4" and no more ".kde" (eg /home/user/.kde4).

I propose the following patches against IJ 1.2.x (2010_05_27) which solve the problem by removing the console title :

<pre>
--- lib/Actions/ExecuteActions/ExecuteExternalProgram_original.action   2010-05-27 11:41:06.000000000 +0200
+++ lib/Actions/ExecuteActions/ExecuteExternalProgram.action    2010-05-27 17:48:28.000000000 +0200
@@ -320,8 +320,9 @@
                 }
                 set cmd $tmpfile
 
+                ## "-T $title" option suppressed because KDE4 konsole doesn't support it anymore!
                 if {$konsole} {
-                    set cmd [concat [list $term -T $title] -e $cmd]
+                    set cmd [list $term -e $cmd]
                 } elseif {$gnometerm} {
                     set cmd [list $term -t $title -e $cmd]
                 } else {
</pre>

Link to the matching threak in the forum : http://www.installjammer.com/forums/viewtopic.php?f=1&p=8956

**Comment by damoncourtney** [comment]
Made a patch and pushed it out.  Should be in the release shortly.
