### ISSUE TITLE
Could not open: missing close-brace

### ISSUE THREAD

**Issue by lornemcintosh** [damoncourtney/installjammer#53]
Using InstallJammer version 1.3.0 (Build 6c376a1)

Opening an mpi file saved from an older InstallJammer version, and saving it results in an unreadable file.

Steps to reproduce:
- Open the attached mpi file (written by an earlier version - I can't remember which, but it says ProjectVersion 1.3.0.2 in the .mpi file)
- Save the project (Ctrl+S)
- Attempt to open the new mpi file, and receive the error message:
  "Could not open 'installer.mpi': missing close-brace"

**Comment by damoncourtney** [comment]
This is using the current 1.3 snapshot?

**Comment by lornemcintosh** [comment]
Yes, the 1.3 hourly snapshot. Current as of yesterday.

**Comment by damoncourtney** [comment]
Ok.  I realized that I fixed this in 1.2.15 AFTER I had merged back with the 1.3 branch, so 1.3 doesn't have the fix.  I will be doing a full merge of the 1.2.15 release into the 1.3 branch in the coming week, and that should take care of this.
