### ISSUE TITLE
InstallJammer version 1.2.15 gives error when trying to get the version

### ISSUE THREAD

**Issue by rockyjammer** [damoncourtney/installjammer#55]
Hi ,

I tried to get the version of the installjammer by running the installjammer binary but following error: ( I used 1.2.15 version of installjammer)

./installjammer -version
can't read "conf(BuildVersion)": no such element in array
while executing
"puts "$conf(Version) ($conf(BuildVersion))""
("-version" arm line 2)
invoked from within
"switch -glob -- $opt {
"--build" - "-b" {
# Build the install of the given project.

set conf(cmdline) 1
}

"--build-d..."
(procedure "::ParseCommandLineArgs" line 70)
invoked from within
"::ParseCommandLineArgs"
(procedure "init" line 270)
invoked from within
"init"
invoked from within
"if {!$tcl_interactive} { init; main }"
(file "/usr/local/installjammer/lib/main.tcl" line 871)
invoked from within
"source [file join $conf(pwd) lib main.tcl]"
(file "./installjammer.tcl" line 32)

**Comment by damoncourtney** [comment]
- Fixed a bug where running with --version would fail because of a missing build version.
  Closed by fe0fd7fda7613a0dafca18ab2325b3e96e3f11ec
