### ISSUE TITLE
1.2.15 no longer works on Solaris x86

### ISSUE THREAD

**Issue by ghost** [damoncourtney/installjammer#60]
Hi,

Since upgrading to Installjammer 1.2.15, I can no longer run the program on my Solaris x86 server.

The reason is that this platform reports 'uname -m' as 'i86pc'. The installjammer startup script does not match this value. To fix you need to change line 42 from:
    _86)
to
    *86_)

You then also need to change lib/utils.tcl:2810 from
    "intel" - "_86"
to
    "intel" - "_86*"

Ben

**Comment by damoncourtney** [comment]
- Fixed a bug in platforms that use a weird name for x86.
  Closed by 72d18d60a2516fb4ad0afaae3bac97ba757e64d2
