### ISSUE TITLE
Bug Report - IJ 1.2.15(Beta) Windows Close Button Issue

### ISSUE THREAD

**Issue by dviral** [damoncourtney/installjammer#61]
When IJ's progress bar is getting displayed and when External Program is being executed..,windows close button is working.(while cancel is hidden.)

now the problem is: when user clicks on windows close button Uninstaller exits..,without warning message or anything.

So.., uninstallation cannot be completed successfully.

Actually Windows close button and Cancel of IJ is synchronized with each other and works accordingly.

But, When IJ is executing External program, the windows close button is accessible (which must not be accessible, because cancel is hidden in that pane.)

That's filing a bug.
Please let me know if the information is insufficient or if you want to know something in more detail.

Forum topic URL: http://www.installjammer.com/forums/viewtopic.php?f=3&t=1953

Thank you,
dviral

**Comment by damoncourtney** [comment]
- Fixed a bug where the X button on the window could still cancel the wizard even if the cancel button had been hidden.
  Closed by a746208b4e1b4417c39bb9ecb7ee2f6ab1ab3cc2
