### ISSUE TITLE
Encoding property isn't getting substituted for virtual text before passing along to the action

### ISSUE THREAD

**Issue by briansummers** [damoncourtney/installjammer#63]
I'm using IJ 1.2.15

I set a Virtual Text String as follows:

targetEncoding = cp850

When I use:

<%targetEncoding%> 

in the Encoding field of the Replace Text in File Action it doesn't seem to get translated:

Error in action ExecuteAction

Error in action ReplaceTextInFile

unknown encoding "<%targetEncoding%>"
    while executing
"fconfigure $fp -encoding $props(Encoding)"
    (procedure "::InstallJammer::actions::ReplaceTextInFile" line 19)
    invoked from within
"::InstallJammer::actions::$component $this"
    while executing
"$obj execute"
    (procedure "::InstallJammer::ExecuteActions" line 69)
    invoked from within
"::InstallJammer::ExecuteActions $action -parent $id -conditions $eval"
    (procedure "::InstallJammer::actions::ExecuteAction" line 35)
    invoked from within
"::InstallJammer::actions::$component $this"
Error in action ExecuteAction

Thanks!

**Comment by damoncourtney** [comment]
- Fixed a bug in Replace Text in File where the Encoding property was not substituted for virtual text.
  Closed by 275c9c296d7ae59eb8803ca70b59055535e4ee8f
