### ISSUE TITLE
InstallAPI::FetchURL does not handle redirect for Sun AutoDL

### ISSUE THREAD

**Issue by RayzorDuff** [damoncourtney/installjammer#69]
I'm attempting to create an auto download of Sun's JRE using the URL:
http://javadl.sun.com/webapps/download/AutoDL?BundleId=42727

To do this, I've constructed a page that uses checks from the Locate Java Runtime and OS checks before the Fetch URL and Execute External Program calls.  The process is failing, however, during the Fetch.

I see that there is some code already in installapi.tcl for handling a redirect.  I'm not sure what is different about this particular redirect, but perhaps the following link will help?
http://wiki.tcl.tk/11831

As a side note (and I can write up a separate issue if that's preferable), can the Fetch mechanism be updated to store the downloaded file with the execute bit already set?  As it stands, I also need to find a way to set the execute bit on the downloaded Java installer before Execute External Program will pass.

**Comment by damoncourtney** [comment]
I'll have to test with the URL you sent and see why the redirect isn't working properly.

As for an executable bit, you're right.  It should automatically set one after a file is downloaded.  You can always do it yourself with an action or a script, but it feels like one of those things that should just be automatic. 0-]

**Comment by damoncourtney** [comment]
I just pushed a fix for this.  Should be good.  I fixed the redirects and made the default file permissions 0755 when downloading to a file.

**Comment by RayzorDuff** [comment]
Thanks Damon!  Is there any chance you can merge this to the 1.3 branch?  I moved to 1.3 but I can't remember the reason offhand except that it was important.  ;)

**Comment by RayzorDuff** [comment]
Here's the patch for the 1.3 branch.  I've tested this and it looks good.

diff -urN installjammer.orig/lib/Actions/GeneralActions/FetchURL.action installjammer/lib/Actions/GeneralActions/FetchURL.action
--- installjammer.orig/lib/Actions/GeneralActions/FetchURL.action   2010-11-23 22:34:36.000000000 -0700
+++ installjammer/lib/Actions/GeneralActions/FetchURL.action    2011-04-06 16:41:12.393543165 -0600
@@ -46,93 +46,21 @@
                         progress of the download"

 proc ::InstallJammer::actions::FetchURL { obj } {
-    global conf

## \-    global info

## \-    package require http

```
 $obj properties props -subst 1
```

## \-    ::http::config -proxyhost $props(ProxyHost) -proxyport $props(ProxyPort)
-    set list  [split $props(URL) \;]
-    set len   [llength $list]

## \-    set total 0
-    lappend args -url $props(URL)
-    if {$props(Timeout) ne ""} { lappend args -timeout $props(Timeout) }
-    if {$props(ProxyHost) ne ""} { lappend args -proxyhost $props(ProxyHost) }
-    if {$props(ProxyPort) ne ""} { lappend args -proxyport $props(ProxyPort) }
   if {$props(ProgressVirtualText) ne ""} {
-        ::InstallAPI::SetVirtualText \

## \-            -virtualtext $props(ProgressVirtualText) -value 0 -autoupdate 1
-        foreach url $list {
-            set tok [::http::geturl $url -validate 1]
-            upvar #0 $tok state
-            incr total $state(totalsize)
-            ::http::cleanup $tok

## \-        }
-        ::InstallJammer::StartProgress \
-            ::info($props(ProgressVirtualText)) $total
- ```
     lappend args -progressvirtualtext $props(ProgressVirtualText)
  ```
  
   }
-    set i 0
-    foreach url $list {
-        incr i
-        set url  [string trim $url]

## \-        set opts [list -blocksize 8192]
-        if {[string length $props(Timeout)]} {
-            #lappend opts -timeout $props(Timeout)

## \-        }
-        if {$props(SaveTo) eq "file" && $props(Target) ne ""} {

## \-            set filename [string trim $props(Target)]
-            if {[file isdirectory $filename]} {
-                set dirname  $filename
-                set filename [file join $dirname [::InstallJammer::uuid].part]

## \-            }
-            set fp [open $filename w]

## \-            fconfigure $fp -translation binary
-            lappend opts -channel $fp

## \-        }
-        if {$total > 0} {
-            ::InstallJammer::ResetProgress
-            lappend opts -progress ::InstallJammer::UpdateProgress

## \-        }
-        if {$len == 1} {
-            set info(Status) "<%DownloadingFilesText%>"
-        } else {
-            set info(Status) "<%DownloadingFilesText%> ($i/$len)"

## \-        }
-        if {[catch { eval ::http::geturl [list $url] $opts } token]} {
-            if {[info exists fp]} { close $fp }
-            if {[info exists filename]} { file delete -force $filename }
-            return -code error $token

## \-        }

## \-        upvar #0 $token state
-        if {$props(SaveTo) eq "file"} {

## \-            close $fp
-            if {[info exists dirname]} {
-                set name [file join $dirname [file tail $state(url)]]
-                file rename -force $filename $name
-                unset dirname filename
-            }

## \-        }
-        if {$props(SaveTo) eq "virtualtext" && $props(Target) ne ""} {
-            set ::info($props(Target)) $state(body)

## \-        }
-        ::http::cleanup $token
-    if {$props(SaveTo) eq "file"} {
-        lappend args -file $props(Target)
-    } else {
- ```
     lappend args -virtualtext $props(Target)
  ```
  
   }
-    if {[info exists var]} { set $var 100 }
-    eval ::InstallAPI::FetchURL $args
  }
  diff -urN installjammer.orig/lib/installapi.tcl installjammer/lib/installapi.tcl
  --- installjammer.orig/lib/installapi.tcl   2010-11-23 22:34:38.000000000 -0700
  +++ installjammer/lib/installapi.tcl    2011-04-15 11:08:35.842009365 -0600
  @@ -369,6 +369,9 @@
  }
  
  proc ::InstallAPI::FetchURL { args } {
  +
-    global conf
  +
   ::InstallAPI::ParseArgs _args $args {
       -blocksize           { string 0 "8192" }
       -file                { string 0 "" }
  @@ -502,6 +505,10 @@
       }
  
  ```
   http::cleanup $token
  ```
  
  +
-        if {[file exists $file] && !$conf(windows)} {
-            file attributes $file -permissions 00755
- ```
     }
  ```
  
   }
  
   return 1
  @@ -2433,12 +2440,12 @@
  
   if {$code == 200} {
       set return 1
-    } elseif {$code == 302} {
-    } elseif {[string match {30[1237]} $code]} {
       ## This URL is a redirect.  We need to fetch the redirect URL.
       array set meta $state(meta)
  
  ```
   if {![info exists meta(Location)]} {
  ```
-            return -code error "302 Redirect without new Location"
- ```
         return -code error "$code Redirect without new Location"
   }
  
   set _args(-url) $meta(Location)
  ```
