### ISSUE TITLE
Tcl script takes 40 minutes to open

### ISSUE THREAD

**Issue by gondim2** [damoncourtney/installjammer#84]
I don´t know if it´s because an update to Windows 7 were made, but I have a huge Tcl script (1470 lines, with some functions and procedures) that usually took 2-3 minutes to open in Windows XP, but now it takes exactly 40 minutes to open!
I´m using Windows 7 Enterprise + InstallJammer 1.2.15 (Build c2cf97c).

Thanks.

**Comment by damoncourtney** [comment]
Uh... Can you tell me what this script is doing?  Unless you're doing some OS-specific stuff in there, there's absolutely no reason some Tcl script should run any differently on different versions of Windows.

**Comment by gondim2** [comment]
It does lots of things, but I believe that the hard one is some database commands via tcldb::database::odbc 2.0.
There are others scripts that access database, but they are smaller and are opened fast. It looks like that the size of the script is that let it slow. I can send the script if you want to.
