### ISSUE TITLE
Message Box works 'After Pane is Displayed' only

### ISSUE THREAD

**Issue by tim-caper** [damoncourtney/installjammer#93]
I did not try all options but 'Befor Pane is Finished', 'After Pane is Finished' or 'Before Next Pane is Displayed' are not working for me - the message box is just not displayed, no error indication.

There are two issues here:
1. If some option(s) can not be supported because of some reason, then, at the very least, the limitation should be documented. Ideally, the unsupported options should be unavailable.
1. The limitation itself forced me to duplicate code: as I can not display the box at the end of pane, so I attached it to the beginning of next pane, which is conditional... so I have to attach the same message box to all possible next panes.

InstallJammer 1.2.15 on Red Hat Linux.

**Comment by damoncourtney** [comment]
This may be a misunderstanding of what those action levels do.  What are you trying to do exactly?

Before / After Pane is Finished means to execute this action IF the pane in question is the LAST pane in the installer.  Meaning that the pane will actually FINISH the installation.  It's only useful on the last pane of the installer.  It's actually quite confusing and a holdover from before IJ had the Finish Actions group and the like.

Before Next Pane is Displayed should work if you're trying to launch a message box when the user hits next, but like I said, I don't know what you're trying to do, so I don't know if that's what you want.

**Comment by tim-caper** [comment]
I need to display the message box right before (or after) some pane (in the middle of install) be closed - rather than right after it is open. In the other words at the pane finish rather than start.

**Comment by damoncourtney** [comment]
So, as the user hits Next but BEFORE they proceed to the next pane?  And Before Next Pane is Displayed doesn't work for you?

**Comment by tim-caper** [comment]
> So, as the user hits Next but BEFORE they proceed to the next pane?
> Yes
> 
> And Before Next Pane is Displayed doesn't work for you?
> Yes

**Comment by damoncourtney** [comment]
Do you have any conditions Before Next Pane is Displayed?  If those conditions fail for any reason, the actions will not be executed.  The installer will stop as soon as the conditions fail.

**Comment by tim-caper** [comment]
Do you mean conditions attached to the Message Box? This is not the case.

**Comment by tim-caper** [comment]
Hm-m, if you mean condition attached to the next pane, then this is exactly the case.
And I need to display the box before the next displayed pane, whichever pane it could be... Looks like currently there is no intentional way for it, am I missing something?

**Comment by damoncourtney** [comment]
If you're trying to do what I THINK you're trying to do, you're probably trying to post an error message because your conditions failed.  If that is the case, you want to use the Failure Message property on your conditions.  This message will display as an error dialog if the condition fails for any reason.

This lets you post a different error message for each condition depending on what fails.  If that's not exactly what you're trying to do, there may be some other thing we can do to get you where you're going.

**Comment by tim-caper** [comment]
Hm-m, no :-) I am trying to inform user about Java location right before components selection OR file copying (in case the setup is not custom).

**Comment by damoncourtney** [comment]
Well, if you have a condition on the pane that checks Before Next Pane is Executed, and that fails, they can't move forward to the next pane anyway, so what good is showing them a message box?  The message box will show when the conditions pass and they can actually move forward.

**Comment by tim-caper** [comment]
The next pane is hidden (in fact it is Components pane in Typical setup) but they do can move forward because there is next pane after it. :-)

**Comment by damoncourtney** [comment]
I'm beginning to think I need to see your project file.  I must be missing something here because I'm not seeing the picture.  Can you email me your project file to take a look and point me to the area in question?

**Comment by tim-caper** [comment]
I am not quite sure I can because of NDA.
Anyway, I've rewrote it so now I have what I want by cost of duplicate code.
I will think if I can make some other illustration for the issue.
